name: Pyrefly

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions: read-all

jobs:
  pyrefly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Pyrefly
        run: |
          python -m pip install --upgrade pip
          pip install 'pyrefly==0.29.0'
      - name: Type check with Pyrefly
        run: |
          # Uses your existing [tool.pyrefly] config in pyproject.toml
          pyrefly check
